name: Sync Upstream

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时运行一次
  push:
    branches:
      - chxm1023
      - Loon
      - Surge
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出当前仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Git 用户信息
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      # 添加上游仓库
      - name: Add upstream repository
        run: git remote add upstream https://github.com/chxm1023/Rewrite.git

      # 拉取上游仓库的更新
      - name: Fetch upstream changes
        run: git fetch upstream

      # 同步多个分支
      - name: Sync with upstream
        run: |
          for branch in chxm1023 Loon Surge main; do
            # 检查上游是否有对应分支
            if git show-ref --quiet refs/remotes/upstream/$branch; then
              echo "Syncing branch $branch"
              git checkout $branch || git checkout -b $branch --track origin/$branch
              git pull origin $branch --rebase || true  # 如果远程不存在，跳过 pull
              git merge upstream/$branch --allow-unrelated-histories -m "Sync with upstream $branch" || true
              git push origin $branch --force-with-lease || true
            else
              echo "Branch $branch does not exist in upstream. Skipping..."
            fi
          done
