name: Sync Upstream

on:
  schedule:
    # 每小时同步一次，可以根据需要调整 cron 表达式
    - cron: '0 * * * *'
  push:
    branches:
      - main
      - chxm1023
      - Loon
      - Surge  # 可以在此处列出所有需要同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出当前仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Git 用户信息
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

      # 添加上游仓库
      - name: Add upstream repository
        run: git remote add upstream https://github.com/chxm1023/Rewrite.git

      # 拉取上游仓库的更新
      - name: Fetch upstream changes
        run: git fetch upstream

      # 同步多个分支
      - name: Sync with upstream
        run: |
          for branch in main dev feature; do
            git checkout $branch
            git merge upstream/$branch --allow-unrelated-histories -m "Sync with upstream $branch"
            git push origin $branch
          done
